<html>
<body leftmargin='10.0' rightmargin='10.0' topmargin='10.0' bottommargin='10.0' style='font-family: Arial; font-size: 14.0pt; '>
    <div>
          <table style='font-size:8.0pt; font-family:Arial;  border: 0.5px thick #000000; border-collapse: collapse; width: 1500pt;'>
        <tr>
          <td colspan='2' style='text-align:left; padding: .1pt .1pt .1pt .1pt;'>
             <p style='color: green;line-height: 12.0pt' >
              
             </p>	
          </td>
          <td colspan='4' style='text-align:left; padding: .1pt .1pt .1pt .1pt;'>
             <p style='color: black;line-height: 12.0pt' >
              <b><span style='font-size:16.0pt;font-family:Arial;color:00a8ff'>CUSTOMER DETAILS</span></b>
             </p>	
          </td>
        </tr>
        <tr>
        <td colspan='6' style='text-align:left; background-color:00b894;'>
             <br/>
          </td>
        </tr>
      </table>
      <div>
          </div>
          <div leftmargin='36.0' rightmargin='36.0' topmargin='36.0' bottommargin='36.0'>
          <table style='font-size:8.0pt; font-family:Arial; border-collapse: collapse; width: 900pt;'>
        <tr>
          <td style='text-align:left; width:50%;padding: .1pt .1pt .1pt .1pt;'>
             <p style='line-height: 12.0pt' >
              <b><span style='font-size:10.0pt;font-family:Arial;'>Customer Number &nbsp; : &nbsp; $data.customerId$ </span></b>
             </p>	
          </td>
          <td style='text-align:left; width:50%;padding: .1pt .1pt .1pt .1pt;'>
             <p style='line-height: 12.0pt' >
              <b><span style='font-size:10.0pt;font-family:Arial;'>Customer Name  &nbsp; : &nbsp; $data.name$</span></b>
             </p>	
          </td>
        </tr>
        <tr>
          <td style='text-align:left; width:50%; padding: .1pt .1pt .1pt .1pt;'>
             <p style='line-height: 12.0pt' >
              <b><span style='font-size:10.0pt;font-family:Arial;'> Email  &nbsp; : &nbsp; $data.email$</span></b>
             </p>	
          </td>
          <td style='text-align:left; width:50%; padding: .1pt .1pt .1pt .1pt;'>
             <p style='line-height: 12.0pt' >
              <b><span style='font-size:10.0pt;font-family:Arial;'>Phone Number  &nbsp; : &nbsp; $data.phoneNo$</span></b>
             </p>	
          </td>
        </tr>
        <tr>
          <td style='text-align:left; width:50%; padding: .1pt .1pt .1pt .1pt;'>
             <p style='line-height: 12.0pt' >
              <b><span style='font-size:10.0pt;font-family:Arial;'> Gender  &nbsp; : &nbsp; $data.gender$</span></b>
             </p>	
          </td>
          <td style='text-align:left; width:50%; padding: .1pt .1pt .1pt .1pt;'>
             <p style='line-height: 12.0pt' >
              <b><span style='font-size:10.0pt;font-family:Arial;'>Address  &nbsp; : &nbsp; $data.address$</span></b>
             </p>	
          </td>
        </tr>
        <tr>
          <td colspan=2 style='width:100%;'>
             <p style='line-height: 12.0pt' >
             </p>	
          </td>
        </tr>			
      </table>
      <div>

          </div>
          
      <table style='font-size:8.0pt; font-family:Arial;  border: 0.5px thick #000000; border-collapse: collapse; width: 900pt;'>
        <tr>
          <td colspan='2' style='padding: .1pt .1pt .1pt .1pt; width : 100%'><b><span style='font-size:10.0pt;font-family:Arial;'>Policies Details :</span></b></td>
        </tr>	
        $policies$
      
      </table>
      <div><br/></div>
      </div>
</div>
</body>
</html>	